import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  header: {
    width: 150, height: 50, justifyContent: 'space-around',
  },
  image: {
    flex: 1,
    width: 425,
  },
  flipcard2: {
    width: 250, height: 300,
  },
  FlightSearchContainer: {
    flex: 1,
    backgroundColor: 'grey',
  },
  FlightSearchHeader: {
    backgroundColor: '#E91E63',
    alignItems: 'center',
    borderBottomWidth: 10,
    borderBottomColor: '#ddd',
    height: 150,
  },
  FlightSearchHeaderText: {
    color: 'white',
    fontSize: 30,
    paddingTop: 70,
  },
  FlightSearchToTextInput: {
    color: 'black',
    fontSize: 20,
    position: 'absolute',
    left: 3,
    top: 160,
    alignItems: 'center',
    justifyContent: 'center',
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: 'black',
    alignSelf: 'center',
  },
  FlightSearchFromTextInput: {
    color: 'black',
    fontSize: 20,
    position: 'absolute',
    right: 3,
    top: 160,
    alignItems: 'center',
    justifyContent: 'center',
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: 'black',
    alignSelf: 'center',
  },
  contentCenter: {
    bottom: 150,
    left: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  FlightSearchSourceTextInput: {
    color: 'black',
    fontSize: 20,
    position: 'absolute',
    right: 200,
    top: 250,
    alignItems: 'center',
    justifyContent: 'center',
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: 'black',
    alignSelf: 'center',
  },
  FlightSearchDestinationTextInput: {
    color: 'black',
    fontSize: 20,
    position: 'absolute',
    right: 175,
    top: 300,
    alignItems: 'center',
    justifyContent: 'center',
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: 'black',
    alignSelf: 'center',
  },
  FlightSearchPassengersTextInput: {
    position: 'absolute',
    color: 'black',
    fontSize: 20,
    top: 350,
    right: 155,
    alignItems: 'center',
    justifyContent: 'center',
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: 'black',
    alignSelf: 'center',
  },
  FlightSearchsubmit: {
    zIndex: 11,
    top: 250,
    left: 175,
    backgroundColor: '#E91E63',
    width: 100,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
  },
  ButtonText: {
    color: 'white',
    fontSize: 20,
  },
  FlightResultAiline: {
    zIndex: 11,
    top: 20,
    backgroundColor: 'rgb(32,137,180)',
    width: 300,
    height: 165,
    borderRadius: 10,
    left: 3,
    elevation: 10,
  },
  UserDetailsText: {
    color: 'black',
    fontSize: 20,
    position: 'absolute',
    left: 3,
    top: 160,
    alignSelf: 'center',

  },
  UserDetailsTextPassengers: {
    color: 'black',
    fontSize: 20,
    position: 'absolute',
    left: 3,
    top: 210,
    alignSelf: 'center',
  },
  UserDetailsTextInput: {
    position: 'absolute',
    color: 'black',
    fontSize: 20,
    top: 300,
    right: 180,
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: '#91194d',
    alignSelf: 'center',
  },
  UserDetailsAgeTextInput: {
    position: 'absolute',
    color: 'black',
    fontSize: 20,
    top: 350,
    right: 210,
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: '#91194d',
    alignSelf: 'center',
  },
  UserDetailsPassportTextInput: {
    position: 'absolute',
    color: 'black',
    fontSize: 20,
    top: 400,
    right: 180,
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: '#91194d',
    alignSelf: 'center',
  },
  Paysubmit: {
    zIndex: 11,
    top: 350,
    left: 155,
    backgroundColor: '#E91E63',
    width: 100,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
  },
  ConformationText: {
    color: 'black',
    fontSize: 25,
    paddingTop: 70,
  },
  ConformationSubmit: {
    zIndex: 11,
    top: 20,
    left: 195,
    backgroundColor: '#E91E63',
    width: 100,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
  },
  planePic: {
    width: 200,
    height: 85,
  },
  FlightResultAilines: {
    zIndex: 11,
    top: 100,
    backgroundColor: 'rgb(32,137,180)',
    width: 300,
    height: 165,
    borderRadius: 10,
    left: 3,
    elevation: 10,
  },
  UserDetailsTextCost: {
    color: 'black',
    fontSize: 20,
    position: 'absolute',
    left: 3,
    top: 250,
    alignSelf: 'center',
  },
});
export default styles;
